name: Go Test

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
  pull_request:
    paths:
      - "server/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.1

      - name: Install dependencies
        working-directory: ./server
        run: go mod tidy

      # 4. テストを実行
      - name: Run tests
        working-directory: ./server
        run: go test ./... -v
