name: VSCode Client Test

on:
  push:
    branches:
      - main
    paths:
      - "vscode_client/**"
  pull_request:
    paths:
      - "vscode_client/**"

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23.0.0"

      - name: Install dependencies
        working-directory: ./client
        run: npm ci

      - name: Run TypeScript Type Check
        working-directory: ./client
        run: npx tsc --noEmit
